#!/bin/bash

python3 -m grpc_tools.protoc ./lego_sorter_server/proto/*.proto \
  --proto_path=./lego_sorter_server/proto                       \
  --python_out=./lego_sorter_server/generated                   \
  --grpc_python_out=./lego_sorter_server/generated

for file in lego_sorter_server/generated/*.py; do
  sed -e 's/^import \(.*\) as \(.*\)/import lego_sorter_server.generated.\1 as \2/g' -i $file
done